altschool_blog_project/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):

    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

altschool_blog_project/main/routes.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from altschool_blog_project.main.forms import ContactForm
from altschool_blog_project.models import Post, Message
from altschool_blog_project import db


main = Blueprint('main', __name__)


@main.route('/')
def home():

    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page = page, per_page = 5)

    return render_template('home.html', posts = posts)

@main.route('/about')
def about():

    return render_template('about.html')



@main.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if form.validate_on_submit():

        name = form.name.data
        email = form.email.data
        message = form.email.data

        contact_message = Message(name = name, email = email, message = message)

        db.session.add(contact_message)
        db.session.commit()

        flash('Your Message has Been Sent, we will get back to you soon!!', 'success')

        return redirect(url_for('main.home'))

        

    return render_template('contact.html', form = form, title = 'Contact')

altschool_blog_project/posts/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort
from altschool_blog_project import db, login_manager
from flask_login import login_required, current_user
from altschool_blog_project.models import Post
from altschool_blog_project.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/posts/new', methods=['GET', 'POST'])
@login_required
def create_post():

    form = PostForm()
    if form.validate_on_submit():

        title = form.title.data
        content = form.content.data
        post = Post(title = title, content= content, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post Has Been Created', 'success')

        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Create Post', form = form, legend = 'Add A New Post')

@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    
    post = Post.query.get_or_404(post_id)

    return render_template('post.html', title= post.title, post = post, legend = 'New Post' )

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    
   
    form = PostForm()

    if form.validate_on_submit():
        
        post.title = form.title.data
        post.content = form.content.data

        db.session.commit()

        flash('Your Post Has been Updated', 'success')

        return redirect(url_for('posts.post', post_id = post.id))

    elif request.method == 'GET':

        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html', title= post.title, form = form, legend = 'Update Post' )


@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    
    else:
        db.session.delete(post)
        db.session.commit()

        flash('Your Post Has been Deleted', 'success')

        return redirect(url_for('main.home'))

altschool_blog_project/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from altschool_blog_project.users.forms import RegistrationForm, LoginForm, UpdateProfileForm, ResetPasswordForm, ResetRequestForm
from flask_login import current_user, login_user, logout_user, login_required
from altschool_blog_project import db, bcrypt
from altschool_blog_project.models import User, Post
from altschool_blog_project.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    if form.validate_on_submit():
        
        
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        name = form.username.data
        email = form.email.data
        user = User(username = name, email = email, password = hashed_password)

        db.session.add(user)
        db.session.commit()
        flash(f' Account Created For {form.username.data}! You can now Log In', 'success')
        return redirect(url_for('users.login'))


    return render_template('register.html', title = 'Register', form = form)

@users.route('/login', methods= ['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email = form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):

            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')

            

            return redirect(next_page ) if next_page else redirect(url_for('main.home'))    

        else:
            flash('Log In failed, Use The Right Credentials', 'danger')


    return render_template('login.html', title='Login', form = form)

@users.route('/logout')
def logout():

    logout_user()

    return redirect(url_for('main.home'))

@users.route('/profile', methods = ['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfileForm()

    if form.validate_on_submit():

        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
 
        current_user.username = form.username.data
        current_user.email = form.email.data

        db.session.commit()

        flash('Your Profile has been Updated', 'success')

        return redirect(url_for('users.profile'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email


    image_file = url_for('static', filename = 'profile_pics/'+current_user.image_file)
    return render_template('profile.html', title = 'Profile', image_file = image_file, form = form)

@users.route('/user/<int:user_id>/posts', methods=['GET', 'POST'])
@login_required
def get_user_posts(user_id):
    
    page = request.args.get('page', 1, type=int)
    author = User.query.get_or_404(user_id)
    
    posts = Post.query.filter_by(author = author).order_by(Post.date_posted.desc()).paginate(page=page, per_page = 5)

    return render_template('user_posts.html', title = author.username, author = author, posts = posts)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = ResetRequestForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)

        flash('An Email Has Been Sent WIth Instructions on How To Change The Password', 'success')

        return redirect(url_for('users.login'))

    return render_template('reset_request.html', title = 'Reset Password', form = form)



@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)

    if user is None:
        flash('The Token Is Invalid or Expired', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password


        db.session.commit()
        flash(f' Your Password has been changed. You can now Log In', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password.html', title= "Reset PassWord", form = form)

altschool_blog_project/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <div class="jumbotron">
            <h3 class="display-4"> About The Page </h3>
            <p class="article-content">
                This Blog Was created In Service of the ALTSCHOOL second Semester Project. 

                Hopefully I did well.
            </p>
        </div>
    </div>
{% endblock %}

altschool_blog_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title> Page </title>
    {%endif%}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md bg-steel fixed-top" >
            <div class="container-fluid">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                    <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                    <a class="nav-item nav-link" href="{{url_for('main.contact')}}">Contact Us</a>
                </div>
                    
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{url_for('users.profile')}}"> Profile </a>
                        <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Log Out</a>
                        <a class="nav-item nav-link" href="{{url_for('posts.create_post')}}">Add New Post</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                        <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                    {%endif%}
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {%if messages%}
                        {% for category, message in messages %}
                            <div class="alert alert-{{category}}">
                                {{message}}
                            </div>
                        {% endfor %}
                    {%endif%}
                {% endwith %}
                {% block content %}  {% endblock %}
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>

</body>
</html>

altschool_blog_project/templates/contact.html
{% extends 'base.html' %}
{% block content %}

    <div class="content-section">
        <div class="jumbotron">
            <h2 class="display-4"> Would You Like To Reach Out?? </h2>
            <a href="mailto:temitopeadebayo749@gmail.com" class="btn btn-secondary m-1"> Send us An Email </a> <br>
            <a href="tel:+2349061780323" class="btn btn-secondary m-1"> Or Call Us </a>
        </div>
    </div>

    <div class="content-section" >
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Contact Us</legend>
                <div class="form-group">
                    {{form.name.label(class="form-control-label")}}
                    {% if form.name.errors %}
                        {{form.name(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>
                    {% else %}
                        {{form.name(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="inavlid-feedback">
                            {% for error in form.email.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>

                    {% else %}
                        {{form.email(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.message.label(class="form-control-label")}}
                    {% if form.message.errors %}
                        {{form.message(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.message.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>

                    {% else %}
                        {{form.message(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                

            </fieldset>
            <br>
            <div class="form-group">
                {{form.submit (class="btn btn-outline-info")}}                   
            </div>
        </form>

    </div>

{% endblock content %}

altschool_blog_project/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section" >
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> {{legend}} </legend>
                <div class="form-group">
                    {{form.title.label(class="form-control-label")}}
                    {% if form.title.errors %}
                        {{form.title(class="form-control form-control-lg is-invalid")}}
                        <div class="inavlid-feedback">
                            {% for error in form.title.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>

                    {% else %}
                        {{form.title(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.content.label(class="form-control-label")}}
                    {% if form.content.errors %}
                        {{form.content(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>

                    {% else %}
                        {{form.content(class="form-control form-control-lg")}}
                    {% endif %}

                    <br>
                    <br>
            </fieldset>
            <div class="form-group">
                {{form.submit (class="btn btn-outline-info")}}                   
            </div>

        </form>

    </div>
{% endblock content %}

altschool_blog_project/templates/home.html
{% extends "base.html" %}
{% block content %}

    {% for post in posts.items %}
        <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/'+post.author.image_file)}}" alt="">
                <a class="mr-2" href="{{url_for('users.get_user_posts', user_id = post.user_id)}}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d ') }}</small>
            </div>
            <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article>     
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{url_for('main.home', page = page_num)}}"> {{page_num}} </a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{url_for('main.home', page = page_num)}}"> {{page_num}} </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}

altschool_blog_project/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="content-section" >
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login Now </legend>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="inavlid-feedback">
                        {% for error in form.email.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                    </div>

                {% else %}
                    {{form.email(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                    {{form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                    </div>

                {% else %}
                    {{form.password(class="form-control form-control-lg")}}
                {% endif %}
            <div class="form-check">
                {{form.remember(class="form-check-input")}}
                {{form.remember.label(class="form-check-label")}}
            </div>

        </fieldset>
        <div class="form-group">
            {{form.submit (class="btn btn-outline-info")}}                   
        </div>

        <small class="text-muted ml-2">
            <a href="{{url_for('users.reset_request')}}"> Forgot Password?</a>
        </small>
    </form>

</div>

<div class="border-top pt-3">
    <small class="text-muted">
        Dont Have an Account? <a class="ml-2" href="{{url_for('users.register')}}"> Register Here </a>
    </small>
</div>
{% endblock %}

altschool_blog_project/templates/post.html
{% extends "base.html" %}
{% block content %}

    
    <article class="media content-section">
        <div class="media-body">
        <div class="article-metadata">
            <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/'+post.author.image_file)}}" alt="">
            <a class="mr-2" href="{{url_for('users.get_user_posts', user_id = post.user_id)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d ') }}</small>
            {% if post.author == current_user %}
                <div class="">
                    <a href="{{url_for('posts.update_post', post_id = post.id )}}" class="btn btn-secondary btn-sm m-1"> Update </a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal"> Delete</button>

                </div>
            {% endif %}
        </div>
        <h2 class="article title"> {{ post.title }} </h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are You Sure You Want To Delete
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <form action="{{url_for('posts.delete_post', post_id = post.id)}}" method="post">
                <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
    </div>

{% endblock content %}

altschool_blog_project/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{image_file}}">
        <div class="media-body">
            <h2 class="account-heading">{{current_user.username}}</h2>
            <p class="text-secondary">{{current_user.email}}</p>
        </div>
        </div>
        <div class="content-section" >
            <form method="POST" action="" enctype="multipart/form-data">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Update Profile Info </legend>
                    <div class="form-group">
                        {{form.username.label(class="form-control-label")}}
                        {% if form.username.errors %}
                            {{form.username(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                            </div>
                        {% else %}
                            {{form.username(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.email.label(class="form-control-label")}}
                        {% if form.email.errors %}
                            {{form.email(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
    
                        {% else %}
                            {{form.email(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <br>
                    <div class="form-group">
                        {{form.picture.label(class="form-control-label")}} <br>
                        {{form.picture(class="form-contrl-file")}} <br>
                        {%if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">
                                    {{ error }}
                                </span>
                                <br>
                            {% endfor %}                            
                        {%endif%}
                    </div>
    
                </fieldset>
                <br>


                <div class="form-group">
                    {{form.submit (class="btn btn-outline-info")}}                   
                </div>
            </form>
    
        </div>
    
        <div class="border-top pt-3">
            
        </div>
    </div>
{% endblock content %}

altschool_blog_project/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-section" >
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Our Page Now</legend>
                <div class="form-group">
                    {{form.username.label(class="form-control-label")}}
                    {% if form.username.errors %}
                        {{form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>
                    {% else %}
                        {{form.username(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="inavlid-feedback">
                            {% for error in form.email.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>

                    {% else %}
                        {{form.email(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>
                                {{ error }}
                            </span>
                        {% endfor %}
                        </div>

                    {% else %}
                        {{form.password(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.confirm_password.label(class="form-control-label")}}
                    {% if form.confirm_password.errors %}
                        {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
                       <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                            <span>
                                {{ error }}
                            </span>
                            {% endfor %}
                       </div>
                    {% else %}
                        {{form.confirm_password(class="form-control form-control-lg")}}
                    {% endif %}
                </div>


            </fieldset>
            <div class="form-group">
                {{form.submit (class="btn btn-outline-info")}}                   
            </div>
        </form>

    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{url_for('users.login')}}">Sign In</a>
        </small>
    </div>
{% endblock content %}

altschool_blog_project/templates/reset_request.html
{% extends 'base.html' %}

{% block content %}
<div class="content-section" >
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password </legend>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="inavlid-feedback">
                        {% for error in form.email.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                    </div>

                {% else %}
                    {{form.email(class="form-control form-control-lg")}}
                {% endif %}
            </div>
 

        </fieldset>
        <div class="form-group">
            {{form.submit (class="btn btn-outline-info")}}                   
        </div>


    </form>

</div>


{% endblock %}